### ISSUE TITLE
Bug in anova for comparing two nested models

### ISSUE THREAD

**Issue by annennenne** [hojsgaard/geepack#2]
There is a bug in `anova()` when comparing two nested models with expressions in the `id`-argument. Here is an example that triggers the bug: 
```
> library(geepack)
> data(respiratory) 

> mgp <- geeglm(outcome ~ treat, 
              data = respiratory,
              id = with(respiratory, interaction(center, id)),
              family = "binomial", corstr = "exchangeable")
> mgp2 <- geeglm(outcome ~ treat + sex + age + baseline, 
              data = respiratory,
              id = with(respiratory, interaction(center, id)),
              family = "binomial", corstr = "exchangeable")

> anova(mgp, mgp2)
Error in eval(substitute(expr), data, enclos = parent.frame()) : 
  invalid 'envir' argument of type 'character'
```
The problem goes away if the `with()` part is removed. It is not necessary to actually use `with()` here, but nonetheless `anova()` should be able to handle it. 

I have traced the error to `geepack:::anovageePrim2()` in geeglm-anova.R line 50:
```
nymm1[,paste(m1call$id)] <- m1$id
```
where 
```
> paste(m1call$id)
[1] "with"                    "respiratory"             "interaction(center, id)"
```
is the source of the bug. Maybe a possible quick fix could be to just name the id variable "id" in nymm1/nymm2, but maybe there could be a risk of overwriting other variables in the data with that name.

**Comment by hojsgaard** [comment]
Thansk. fixed.
