### ISSUE TITLE
Does this issue with handling weights still hold?

### ISSUE THREAD

**Issue by hugesingleton** [hojsgaard/geepack#6]
Dear @hojsgaard, 
I found this article: [An R package for model fitting, model selection and the simulation for longitudinal data with dropout missingness](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7188076/). It states, that:

> To our best knowledge, there is no reliable and available R package for implementing WGEE. Even though in several R functions for GEE estimation, there exist options in the arguments to incorporate the weights for WGEE estimation, for instance, the function geeM in geeM ([McDaniel et al. 2016](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7188076/#R31)) and the function geeglm in geepack, the inference is not reliable under most circumstances because the weight arguments do not properly incorporate the weights for WGEE. Based on our finding, the estimates are only the same as the WGEE estimates from PROC GEE when the “working” correlation structure is independent. To illustrate this, we conducted a simulation study.[...]

Is this true? Is this truly an issue? And finally - if the answers are positive - is this something that could be fixed in geeglm? I admit, I used the "weights" a few times and did not expect it may lead to problems, so now I am a little in fear.

**Comment by hojsgaard** [comment]
Short answers (I do not know the mentioned paper)
1. I don't know
2. I don't know
3. If it is an issue, then I see no reason why one should not be able to fix it in geeglm. As always, a pull request is welcome.
