### ISSUE TITLE
The link is incorrectly reported (yet handled well)

### ISSUE THREAD

**Issue by hugesingleton** [hojsgaard/geepack#7]
The link from the family call is always displayed as "identity", whatever is put to family: log, logit, etc.

![obraz](https://user-images.githubusercontent.com/47183766/160888494-1e966df1-0e94-4ebf-8fc4-4d6ebc1256df.png)

**Comment by hojsgaard** [comment]
It is an unfortunate printing: The printed link = ... is related to the correlation structure, whereas what one specifies in binomial(...) is related to the mean value. There is a lot of room for improvement in the printing, I admit.
